apiVersion: v1
kind: Namespace
metadata:
  name: pb-micro

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pb-micro
  name: pb-search-deployment
  labels:
    app: pb-search-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pb-search-app
  template:
    metadata:
      labels:
        app: pb-search-app
    spec:
      containers:
        - name: search-app-flask
          image: ibrahimulker/pb-search:2.0
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: phonebook-secret
            - configMapRef:
                name: envconfigpb
          
---
apiVersion: v1
kind: Service
metadata:
  namespace: pb-micro
  name: pb-search-service
spec:
  type: NodePort
  selector:
    app: pb-search-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002



