apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pb-micro
  name: pb-cdu-deployment
  labels:
    app: pb-cdu-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pb-cdu-app
  # strategy:
  #   type: RollingUpdate 
  #   # rollingUpdate:
  #   #   maxUnavailable: 2
  #   #   maxSurge: 1 
  template:
    metadata:
      labels:
        app: pb-cdu-app
    spec:
      containers:
      - name: cdu-app-flask
        image: ibrahimulker/pb-web:2.0
        ports:
          - containerPort: 80
        envFrom:
            - secretRef:
                name: phonebook-secret
            - configMapRef:
                name: envconfigpb

---
apiVersion: v1
kind: Service
metadata:
  namespace: pb-micro
  name: pb-cdu-service
spec:
  type: NodePort
  selector:
    app: pb-cdu-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001



